# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  # Schedule updates (each day)
  schedule: [{cron: "0 0 * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: General
      uses: lowlighter/metrics@latest
      with:
        filename: general.svg
        token: ${{ secrets.METRICS_TOKENS }}
        
        user: jk15162428
        template: classic
        base: header, repositories
        plugin_lines: yes
        plugin_isocalendar: yes
        
    - name: Analysis
      uses: lowlighter/metrics@latest
      with:
        filename: analysis.svg
        token: ${{ secrets.METRICS_TOKENS }}
        
        user: jk15162428
        template: classic
        base: ""
        plugin_languages: yes
        plugin_languages_ignored: >-
          html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell,
          gnuplot
        plugin_languages_indepth: yes
        plugin_languages_details: lines, bytes-size
        plugin_languages_limit: 4
        plugin_languages_analysis_timeout: 15
        plugin_followup: yes
        plugin_followup_indepth: yes
        plugin_discussions: yes
        plugin_discussions_categories_limit: 8
        
    - name: LeetCode
      uses: lowlighter/metrics@latest
      with:
        filename: leetcode.svg
        token: ${{ secrets.METRICS_TOKENS }}
        
        user: jk15162428
        template: classic
        base: ""
        plugin_leetcode_limit_recent: 2
        plugin_leetcode_limit_skills: 10
        plugin_leetcode: yes
        plugin_leetcode_sections: solved, skills, recent
        plugin_leetcode_user: jk15162428

